general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # Ensure the screen is locked before suspending.
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn screens back on automatically after waking up.
}

# 1. Dim the screen
listener {
    timeout = 150                                # 2.5 minutes.
    on-timeout = brightnessctl -s set 10         # Lower brightness to 10 (Requires brightnessctl).
    on-resume = brightnessctl -r                 # Restore brightness when activity is detected.
}

# 2. Lock the screen
listener {
    timeout = 300                                 # 5 minutes.
    on-timeout = loginctl lock-session            # Trigger the lock command defined in 'general'.
}

# 3. Turn off displays
listener {
    timeout = 330                                 # 5.5 minutes.
    on-timeout = hyprctl dispatch dpms off        # Turn off the screen to save power.
    on-resume = hyprctl dispatch dpms on          # Turn the screen back on when activity resumes.
}

# 4. Suspend the system
listener {
    timeout = 600                                 # 10 minutes.
    on-timeout = systemctl suspend                # Put the computer to sleep.
}
